# Generated by Django 5.1.15 on 2026-04-08 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_export', '0010_alter_convertedformat_export_type'),
        ('projects', '0034_project_annotator_evaluation_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagedExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('failed', 'Failed'), ('completed', 'Completed')], default='created', max_length=64)),
                ('export_format', models.CharField(default='JSON', max_length=64)),
                ('target_path', models.TextField(help_text='Server directory where exported files are stored')),
                ('include_resources', models.BooleanField(default=False, help_text='Include original data files')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='export_packages')),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaged_exports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
