# Generated by Django 5.1.15 on 2026-04-08 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_project_file_upload_idx_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="review_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comment from reviewer",
                verbose_name="review comment",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                help_text="Review status of this annotation",
                max_length=10,
                null=True,
                verbose_name="review status",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this annotation was reviewed",
                null=True,
                verbose_name="reviewed at",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reviewed this annotation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_annotations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewed by",
            ),
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("reassigned", "Reassigned"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        help_text="Annotator assigned to this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task assigned to annotator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_assignment",
                "indexes": [
                    models.Index(
                        fields=["task", "annotator"],
                        name="task_assign_task_id_f59c56_idx",
                    ),
                    models.Index(
                        fields=["annotator", "status"],
                        name="task_assign_annotat_874c2d_idx",
                    ),
                ],
            },
        ),
    ]
