# Generated by Django 5.1.15 on 2026-04-08 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_alter_fileupload_file'),
        ('projects', '0034_project_annotator_evaluation_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=1024)),
                ('total_size', models.BigIntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
