# Generated by Django 5.1.15 on 2026-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_project_annotator_evaluation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hide_annotations_for_annotators",
            field=models.BooleanField(
                default=False,
                help_text="Hide other annotators results from annotators",
                verbose_name="hide annotations for annotators",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hide_completed_for_annotators",
            field=models.BooleanField(
                default=False,
                help_text="Hide completed tasks from annotators in the task list",
                verbose_name="hide completed for annotators",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reject_flow_mode",
            field=models.CharField(
                choices=[
                    ("back_to_same", "Back to same annotator"),
                    ("back_to_pool", "Back to task pool"),
                ],
                default="back_to_same",
                help_text="Where rejected annotations go",
                max_length=20,
                verbose_name="reject flow mode",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="require_review",
            field=models.BooleanField(
                default=False,
                help_text="Whether annotations require reviewer approval before being marked complete",
                verbose_name="require review",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="task_assignment_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual assignment"),
                    ("auto_round_robin", "Auto round-robin"),
                    ("self_pick", "Self pick from pool"),
                ],
                default="self_pick",
                help_text="How tasks are assigned to annotators",
                max_length=20,
                verbose_name="task assignment mode",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[("AD", "Admin"), ("AN", "Annotator"), ("RE", "Reviewer")],
                default="AN",
                help_text="Role of the user in the project",
                max_length=2,
                verbose_name="role",
            ),
        ),
    ]
