# Generated by Django 5.1.15 on 2026-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[("OW", "Owner"), ("AD", "Admin"), ("ME", "Member")],
                default="ME",
                help_text="Role of the user in the organization",
                max_length=2,
                verbose_name="role",
            ),
        ),
    ]
