export const DEFAULT_HOTKEYS = [
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: "提交标注",
    key: "ctrl+enter",
    description: "提交当前标注结果",
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: "跳过任务",
    key: "ctrl+space",
    description: "跳过当前任务",
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: "撤销",
    key: "ctrl+z",
    description: "撤销上一步操作",
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: "重做",
    key: "ctrl+shift+z",
    description: "恢复刚刚撤销的操作",
    active: true,
  },
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: "聚焦上一个任务",
    key: "shift+up",
    description: "将焦点移动到上一个任务",
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: "聚焦下一个任务",
    key: "shift+down",
    description: "将焦点移动到下一个任务",
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: "聚焦已关闭任务列",
    key: "shift+left",
    description: "将焦点移动到已关闭任务列",
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: "聚焦打开任务列",
    key: "shift+right",
    description: "将焦点移动到打开任务列",
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: "切换批量侧栏",
    key: "shift+.",
    description: "展开或收起批量操作侧栏",
    active: true,
  },
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: "删除全部区域",
    key: "ctrl+backspace",
    description: "移除全部标注区域",
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: "聚焦首个区域",
    key: "enter",
    description: "将焦点移动到第一个可聚焦区域",
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: "创建区域关系",
    key: "alt+r",
    description: "在已选区域之间创建关系",
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: "切换区域可见性",
    key: "alt+h",
    description: "显示或隐藏当前选中区域",
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: "切换全部区域可见性",
    key: "ctrl+h",
    description: "显示或隐藏全部区域",
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: "锁定区域",
    key: "alt+l",
    description: "锁定或解锁当前选中区域",
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: "编辑区域元数据",
    key: "alt+m",
    description: "编辑当前选中区域的元数据",
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: "取消选中区域",
    key: "u",
    description: "取消当前选中的区域",
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: "退出区域模式",
    key: "escape",
    description: "退出关系模式并取消选中区域",
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: "删除当前区域",
    key: "backspace",
    description: "删除当前选中区域",
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: "循环切换区域",
    key: "alt+.",
    description: "在全部区域之间循环切换",
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: "复制区域",
    key: "ctrl+d",
    description: "复制当前选中区域",
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: "删除片段",
    key: "delete",
    description: "删除当前选中片段",
    active: true,
  },
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: "后退 1 秒",
    key: "ctrl+b",
    description: "音频回退 1 秒",
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: "播放或暂停音频",
    key: "ctrl+p",
    description: "切换音频播放状态",
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: "单步后退",
    key: "alt+a",
    description: "后退一帧",
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: "单步前进",
    key: "alt+d",
    description: "前进一帧",
    active: true,
  },
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: "播放或暂停视频",
    key: "ctrl+alt+space",
    description: "切换视频播放状态",
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: "单步后退",
    key: "alt+left",
    description: "后退一帧",
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: "单步前进",
    key: "alt+right",
    description: "前进一帧",
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: "上一关键帧",
    key: "ctrl+alt+left",
    description: "跳转到上一关键帧",
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: "下一关键帧",
    key: "ctrl+alt+right",
    description: "跳转到下一关键帧",
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: "向后搜索",
    key: "alt+left",
    description: "向后搜索视频",
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: "首帧",
    key: "shift+ctrl+alt+left",
    description: "跳转到第一帧",
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: "向前搜索",
    key: "shift+alt+right",
    description: "向前搜索视频",
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: "末帧",
    key: "shift+ctrl+alt+right",
    description: "跳转到最后一帧",
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: "快速后跳",
    key: "shift+alt+left",
    description: "快速向后跳转",
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: "快速前跳",
    key: "shift+alt+right",
    description: "快速向前跳转",
    active: true,
  },
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: "向左扩展",
    key: "left",
    description: "向左扩展当前区域",
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: "向右扩展",
    key: "right",
    description: "向右扩展当前区域",
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: "向左收缩",
    key: "alt+left",
    description: "从左侧收缩当前区域",
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: "向右收缩",
    key: "alt+right",
    description: "从右侧收缩当前区域",
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: "大幅向左扩展",
    key: "shift+left",
    description: "大幅向左扩展区域",
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: "大幅向右扩展",
    key: "shift+right",
    description: "大幅向右扩展区域",
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: "大幅向左收缩",
    key: "shift+alt+left",
    description: "大幅从左侧收缩区域",
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: "大幅向右收缩",
    key: "shift+alt+right",
    description: "大幅从右侧收缩区域",
    active: true,
  },
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: "上一张图片",
    key: "ctrl+left",
    description: "查看上一张图片",
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: "下一张图片",
    key: "ctrl+right",
    description: "查看下一张图片",
    active: true,
  },
  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: "放大",
    key: "ctrl+plus",
    description: "放大图像",
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: "平移图像",
    key: "H",
    description: "在图像上拖动平移",
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: "缩放适应窗口",
    key: "shift+1",
    description: "让整张图像完整显示在视图中",
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: "缩放到 100%",
    key: "shift+2",
    description: "按图像原始尺寸显示",
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: "缩小",
    key: "ctrl+minus",
    description: "缩小图像",
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: "移动工具",
    key: "V",
    description: "选择移动工具以调整标注位置",
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: "画笔工具",
    key: "B",
    description: "选择画笔工具",
    active: true,
  },
  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: "椭圆工具",
    key: "O",
    description: "选择椭圆工具",
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: "橡皮擦工具",
    key: "E",
    description: "选择橡皮擦工具",
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: "自动检测",
    key: "M",
    description: "自动建议可能的区域",
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: "关键点工具",
    key: "K",
    description: "选择关键点标注工具",
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: "魔棒工具",
    key: "W",
    description: "智能选区工具",
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: "多边形工具",
    key: "P",
    description: "选择多边形标注工具",
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: "矩形工具",
    key: "R",
    description: "选择矩形标注工具",
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: "三点矩形",
    key: "shift+R",
    description: "使用三点方式绘制旋转矩形",
    active: true,
  },
  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: "向左旋转",
    key: "alt+left",
    description: "将图像向左旋转 90 度",
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: "向右旋转",
    key: "alt+right",
    description: "将图像向右旋转 90 度",
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: "减小工具尺寸",
    key: "[",
    description: "减小当前工具大小",
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: "增大工具尺寸",
    key: "]",
    description: "增大当前工具大小",
    active: true,
  },
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: "下一句",
    key: "ctrl+down",
    description: "跳转到下一句",
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: "上一句",
    key: "ctrl+up",
    description: "跳转到上一句",
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: "全选并标注",
    key: "ctrl+shift+a",
    description: "选中当前句子的全部文本并创建标注",
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: "下一处区域",
    key: "ctrl+right",
    description: "跳转到当前句子中的下一处区域",
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: "上一处区域",
    key: "ctrl+left",
    description: "跳转到当前句子中的上一处区域",
    active: true,
  },
];

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: "标注操作",
    description: "提交、跳过、撤销、重做等常用标注快捷键",
  },
  {
    id: "data_manager",
    title: "数据管理",
    description: "在项目数据管理页中浏览和操作任务的快捷键",
  },
  {
    id: "regions",
    title: "区域管理",
    description: "创建、选择和操作标注区域的快捷键",
  },
  {
    id: "tools",
    title: "工具",
    description: "图像标注时工具面板相关的快捷键",
  },
  {
    id: "audio",
    title: "音频控制",
    description: "控制音频播放和导航的快捷键",
  },
  {
    id: "video",
    title: "视频控制",
    description: "控制视频播放和导航的快捷键",
  },
  {
    id: "timeseries",
    title: "时序控制",
    description: "操作时序区域的快捷键",
  },
  {
    id: "image_gallery",
    title: "图片集导航",
    description: "多图任务中切换图片的快捷键",
  },
  {
    id: "paragraphs",
    title: "段落导航",
    description: "段落或对话视图中切换句子和区域的快捷键",
  },
];

export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
